"""
API Gateway backend for the human-approval gate in Step 2.

Operator receives an SNS message with two URLs:
  Approve: https://<api>/approve?token=<task-token>&action=approve
  Deny:    https://<api>/approve?token=<task-token>&action=deny

Click approve -> this Lambda calls SendTaskSuccess(token), state machine continues.
Click deny    -> this Lambda calls SendTaskFailure(token), state machine aborts.

The task token is generated by Step Functions when the ManualApprovalGate
state is entered (waitForTaskToken integration pattern).

Environment:
  DR_REGION                  eu-central-1
  APPROVAL_SHARED_SECRET     (optional) value of `sig` query param required
                             to prevent unauthenticated invocations
"""
import hmac
import json
import os
import urllib.parse

import boto3


def _resp(status, body, content_type="text/html"):
    return {
        "statusCode": status,
        "headers": {"Content-Type": content_type},
        "body": body,
    }


def _html(title, message, ok=True):
    color = "#2e7d32" if ok else "#c62828"
    return f"""<!doctype html><html><head><title>{title}</title>
<style>body{{font-family:sans-serif;max-width:560px;margin:64px auto;padding:24px;
background:#fafafa}}h1{{color:{color}}}p{{color:#333}}</style></head><body>
<h1>{title}</h1><p>{message}</p></body></html>"""


def lambda_handler(event, context):
    print(f"[approval] event: {json.dumps(event)}")
    params = event.get("queryStringParameters") or {}
    token = params.get("token")
    action = (params.get("action") or "").lower()
    sig = params.get("sig", "")

    expected_sig = os.environ.get("APPROVAL_SHARED_SECRET", "")
    if expected_sig and not hmac.compare_digest(sig, expected_sig):
        return _resp(403, _html("Forbidden", "Invalid signature.", ok=False))

    if not token:
        return _resp(400, _html("Bad request", "Missing token.", ok=False))
    # Query-string parsing can decode '+' as space, which breaks Step Functions
    # task tokens. Task tokens are base64-like and do not contain literal spaces.
    token = token.replace(" ", "+")
    if action not in ("approve", "deny"):
        return _resp(400, _html("Bad request", "action must be approve or deny.", ok=False))

    sfn = boto3.client("stepfunctions", region_name=os.environ["DR_REGION"])

    if action == "approve":
        try:
            sfn.send_task_success(
                taskToken=token,
                output=json.dumps({
                    "approved": True,
                    "approver_ip": event.get("requestContext", {})
                                          .get("identity", {}).get("sourceIp"),
                }),
            )
            return _resp(200, _html(
                "Approved",
                "DR failover approved. The Step Functions state machine will continue.",
            ))
        except sfn.exceptions.TaskTimedOut:
            return _resp(410, _html(
                "Expired",
                "This approval link has expired (1-hour window). Restart the failover from scratch.",
                ok=False,
            ))
        except sfn.exceptions.InvalidToken:
            return _resp(400, _html(
                "Invalid token",
                "This task token is not valid. It may have been already approved/denied.",
                ok=False,
            ))
        except Exception as e:
            return _resp(500, _html("Error", f"send_task_success failed: {e}", ok=False))

    # action == deny
    try:
        sfn.send_task_failure(
            taskToken=token,
            error="ApprovalDenied",
            cause="Operator denied the DR failover.",
        )
        return _resp(200, _html(
            "Denied",
            "DR failover denied. The Step Functions state machine will terminate.",
        ))
    except Exception as e:
        return _resp(500, _html("Error", f"send_task_failure failed: {e}", ok=False))
