apiVersion: v1
kind: Secret
metadata:
  name: accesshub-runtime
  namespace: accesshub
type: Opaque
stringData:
  baseUrl: "http://prod-aws.accesshub-identity.com"
  tenantId: "SANDBOX"
  nativeSuperadminId: "TESTUSER"
  nativeSuperadminPassword: "crave@123"
  grcApiAccessUser: "grcuser"
  grcApiAccessPassword: "crave@123"
