{{- if and .Values.externalSecret.enabled .Values.externalSecret.secretStoreRef.create (eq .Values.externalSecret.secretStoreRef.kind "ClusterSecretStore") }}
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.externalSecret.secretStoreRef.name }}
  labels:
    {{- include "accesshub.labels" . | nindent 4 }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.externalSecret.secretStoreRef.aws.region | quote }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.externalSecret.secretStoreRef.aws.auth.serviceAccount.name }}
            namespace: {{ .Values.externalSecret.secretStoreRef.aws.auth.serviceAccount.namespace }}
{{- end }}
