{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "accesshub.fullname" . }}-db
  labels:
    {{- include "accesshub.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval | quote }}
  secretStoreRef:
    kind: {{ .Values.externalSecret.secretStoreRef.kind }}
    name: {{ .Values.externalSecret.secretStoreRef.name }}
  target:
    name: {{ .Values.externalSecret.target.name }}
    creationPolicy: {{ .Values.externalSecret.target.creationPolicy }}
  data:
    - secretKey: {{ .Values.global.database.existingSecretUserKey }}
      remoteRef:
        key: {{ .Values.externalSecret.data.username.remoteRef.key | quote }}
        {{- if .Values.externalSecret.data.username.remoteRef.property }}
        property: {{ .Values.externalSecret.data.username.remoteRef.property | quote }}
        {{- end }}
    - secretKey: {{ .Values.global.database.existingSecretPasswordKey }}
      remoteRef:
        key: {{ .Values.externalSecret.data.password.remoteRef.key | quote }}
        {{- if .Values.externalSecret.data.password.remoteRef.property }}
        property: {{ .Values.externalSecret.data.password.remoteRef.property | quote }}
        {{- end }}
{{- end }}
